// <auto-generated />
using System;
using AgroCafeAdmin.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgroCafeAdmin.Data.Migrations
{
    [DbContext(typeof(AgroCafeDbContext))]
    [Migration("20260205030604_AddRegistrosRolesVariedad")]
    partial class AddRegistrosRolesVariedad
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AgroCafeAdmin.Core.Models.Productores.Finca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Anulado")
                        .HasColumnType("bit");

                    b.Property<decimal>("Hectareas")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("ProductorId")
                        .HasColumnType("int");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("ProductorId");

                    b.ToTable("PRO_Fincas", (string)null);
                });

            modelBuilder.Entity("AgroCafeAdmin.Core.Models.Productores.Parcela", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Anulado")
                        .HasColumnType("bit");

                    b.Property<decimal>("Area")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("FincaId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("VariedadId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FincaId");

                    b.HasIndex("VariedadId");

                    b.ToTable("PRO_Parcelas", (string)null);
                });

            modelBuilder.Entity("AgroCafeAdmin.Core.Models.Productores.Productor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Anulado")
                        .HasColumnType("bit");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("PRO_Productores", (string)null);
                });

            modelBuilder.Entity("AgroCafeAdmin.Core.Models.Productores.Variedad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Anulado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("PRO_Variedades", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Anulado = false,
                            Nombre = "Arábica"
                        },
                        new
                        {
                            Id = 2,
                            Anulado = false,
                            Nombre = "Robusta"
                        },
                        new
                        {
                            Id = 3,
                            Anulado = false,
                            Nombre = "Caturra"
                        },
                        new
                        {
                            Id = 4,
                            Anulado = false,
                            Nombre = "Borbón"
                        },
                        new
                        {
                            Id = 5,
                            Anulado = false,
                            Nombre = "Típica"
                        });
                });

            modelBuilder.Entity("AgroCafeAdmin.Core.Models.Seguridad.Roles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Anulado")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SEC_Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Anulado = false,
                            Codigo = "0001",
                            Nombre = "Administrador"
                        },
                        new
                        {
                            Id = 2,
                            Anulado = false,
                            Codigo = "0002",
                            Nombre = "Productor"
                        },
                        new
                        {
                            Id = 3,
                            Anulado = false,
                            Codigo = "0003",
                            Nombre = "Cliente"
                        });
                });

            modelBuilder.Entity("AgroCafeAdmin.Core.Models.Seguridad.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Anulado")
                        .HasColumnType("bit");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contrasenia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.ToTable("SEC_Usuarios", (string)null);
                });

            modelBuilder.Entity("AgroCafeAdmin.Core.Models.Productores.Finca", b =>
                {
                    b.HasOne("AgroCafeAdmin.Core.Models.Productores.Productor", "Productor")
                        .WithMany()
                        .HasForeignKey("ProductorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Productor");
                });

            modelBuilder.Entity("AgroCafeAdmin.Core.Models.Productores.Parcela", b =>
                {
                    b.HasOne("AgroCafeAdmin.Core.Models.Productores.Finca", "Finca")
                        .WithMany()
                        .HasForeignKey("FincaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgroCafeAdmin.Core.Models.Productores.Variedad", "Variedad")
                        .WithMany()
                        .HasForeignKey("VariedadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Finca");

                    b.Navigation("Variedad");
                });

            modelBuilder.Entity("AgroCafeAdmin.Core.Models.Seguridad.Usuario", b =>
                {
                    b.HasOne("AgroCafeAdmin.Core.Models.Seguridad.Roles", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });
#pragma warning restore 612, 618
        }
    }
}
